### ISSUE TITLE
Vault Hook and MySQL Error

### ISSUE THREAD

**Issue by R3miiTV** [Drawethree/PRO-DeathChest#1]
Hey!

Im getting some MySQL and Vault Errors...

Mysql:
https://pastebin.com/kn5EV0yS

Vault:
https://pastebin.com/itRRfQQj

**Comment by Drawethree** [comment]
Hello. Next time please post into PRO-BuildBattle resource issues, this is for PRO-DeathChest. That SQL error is going to be fixed in upcoming version. Vault throws error because you most likely have no economy plugin hooked into it.
