### ISSUE TITLE
Players Cannot Open Chests at All

### ISSUE THREAD

**Issue by Stixil** [Drawethree/PRO-DeathChest#11]
**Describe the bug**
My players cannot open their chests at all, only I am able to open them and I cannot figure out why. They have the following permissions:

deathchestpro.fastloot
deathchestpro.expire.default
deathchestpro.lock
deathchestpro.chest

**To Reproduce**
It happens every time I try to use it. Perhaps a plugin incompatibility?

**Screenshots**
![image](https://user-images.githubusercontent.com/53889383/87231433-30804200-c385-11ea-88bd-510db60e90e2.png)

**Server Information (please complete the following information):**
 - Paper 1.16.1 Version 87

**Comment by Drawethree** [comment]
Hello! Sorry for your issue, going to check the code.

**Comment by Drawethree** [comment]
Should be working properly, please ask on Discord if anyone else is experience such issue.

**Comment by Stixil** [comment]
I had to give .* perms for to work, there's a hidden permission check somewhere I think.
