### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Stixil** [Drawethree/PRO-DeathChest#13]
**Describe the bug**
NPE on trying to remove chests.

**To Reproduce**
Happened after a server restart while chests were active.

**Server Information (please complete the following information):**
 - Paper 1.16.1 version 89

**Additional context**
https://mcpaste.io/a5de1cdef3e20aeb

**Comment by Drawethree** [comment]
Does the issue still happen ? Most likely there was just an issue with integrating PAPI into plugin.

**Comment by Drawethree** [comment]
Should be fixed in 3.4.9. Re-open if still appears.
