### ISSUE TITLE
Fireworks not doing damage with plugin installed.

### ISSUE THREAD

**Issue by Rileybutt** [Drawethree/PRO-DeathChest#18]
Hi I have a issue with the plugin. Whenever it's installed, fireworks stop damaging players entirely. I noticed this after purchasing and installing the plugin and even tested it. I tried turning the fireworks feature for the death chest off, nothing. 

It was only after removing the plugin and testing it again that I was able to do damage with fireworks again. Normally this wouldn't be an issue but players have been using fireworks with Crossbows and now for PvP, it doesn't do anything. I tested it and it's only this plugin, once installed, that the firework damage stops working.

It's only players too. When using it against mobs and entities, the fireworks work fine so it's only players that suddenly don't take any damage.

**Comment by Drawethree** [comment]
Thanks for reporting. I have located the issue. It will be fixed in new version
