### ISSUE TITLE
Chests "appear" at y:-1 when dying in the Void

### ISSUE THREAD

**Issue by PsychoLynx** [Drawethree/PRO-DeathChest#4]
**Describe the bug**
As per the title, when players die in the void, chests "appear" at -1, or rather, they don't. Only the holograms do. Void chests should spawn at y: 1 to be interactable and lootable.
Also, setting "spawn_chest_on_highest_block: true" will spawn the hologram at a decent height, but no chest.

**To Reproduce**
Using version 3.4.0 of the plugin, have stuff in inventory while falling into the void.

**Expected behavior**
The chest should spawn at y=1, not y=-1
**Screenshots**
https://i.imgur.com/9g2PVCv.jpg

**Server Information (please complete the following information):**
 - Java Version: openjdk 1.8.0_242
 - Server Version: git-Paper-225

**Comment by Drawethree** [comment]
Thanks for reporting.
