### ISSUE TITLE
DeathChestPro v3.4.1 generated an exception

### ISSUE THREAD

**Issue by arciniegasdiaz** [Drawethree/PRO-DeathChest#6]
13.04 13:17:44 [Server] Server thread/WARN [DeathChestPro] Task #28 for DeathChestPro v3.4 generated an exception
13.04 13:17:44 [Server] INFO java.util.ConcurrentModificationException: null
13.04 13:17:44 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_242]
13.04 13:17:44 [Server] INFO at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_242]
13.04 13:17:44 [Server] INFO at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_242]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:119) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:106) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.World.getType(World.java:548) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getType(CraftBlock.java:211) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState.update(CraftBlockState.java:181) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockState.update(CraftBlockState.java:171) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at sk.drawethree.deathchestpro.chest.DeathChest.removeChests(DeathChest.java:236) ~[?:?]
13.04 13:17:44 [Server] INFO at sk.drawethree.deathchestpro.chest.DeathChest.removeDeathChest(DeathChest.java:252) ~[?:?]
13.04 13:17:44 [Server] INFO at sk.drawethree.deathchestpro.chest.tasks.ChestRemoveTask.run(ChestRemoveTask.java:22) ~[?:?]
13.04 13:17:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1007) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:955) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:800) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
13.04 13:17:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**_Help please!_**

**Comment by Drawethree** [comment]
Thanks for posting this error, I will fix that shortly :)

**Comment by Drawethree** [comment]
Shoould be fixed in 3.4.8
