### ISSUE TITLE
Teleports go to the exact coordinate instead of .5 offset

### ISSUE THREAD

**Issue by Folas1337** [Drawethree/PRO-DeathChest#9]
**Describe the bug**
When you teleport to your DC you get teleported to the exact (x.0, z.0) coordinates which is the north-west edge of the block intead of a 0.5 offset in x and z direction.
This leads to sometimes not being able to teleport to your DC because you'd be stuck in a wall or other block.

**To Reproduce**
Suicide and teleport to your deathchest

**Expected behavior**
Get teleported to the very middle of the DC block.

**Server Information (please complete the following information):**
 - Java Version 8
 - Server Version: Paper 1.15.2-284

**Comment by Drawethree** [comment]
Fixed in 3.4.8
